<?php

namespace Tests\Unit;
use Tests\TestCase;
use Mockery;
use App\Service\A_HomeService;

/**
*	@group A_HomeService
*/
class A_HomeServiceTest extends TestCase
{
	private $a_HomeService;
	private $profilesRepository;
	public function setUp()
    {
        $this->profilesRepository = Mockery::mock('\App\Repository\Interfaces\ProfilesRepositoryInterface');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        Mockery::close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
	/**
	* @group index
	**/
    public function testIndex()
    {
    	$expected_results = 'home';
    	$this->a_HomeService = new A_HomeService(
    		$this->profilesRepository
    	);
    	$result = $this->a_HomeService->index();
    	$this->assertEquals($result,$expected_results);
    }

    /**
    *	@group logout
    **/
    public function testLogout()
    {
    	$result_logout = true;
    	\Auth::shouldReceive('logout')
    		->times(1)
    		->andReturn($result_logout);
    	$expected_results = 'login';
    	$this->a_HomeService = new A_HomeService(
    		$this->profilesRepository
    	);
    	$result = $this->a_HomeService->logout();
    	$this->assertEquals($result,$expected_results);
    }
}