<?php

namespace Tests\Unit;
use Tests\TestCase;
use Mockery;
use App\Service\S_IndexService;

/**
*	@group S_IndexService
*/
class S_IndexServiceTest extends TestCase
{
	private $s_IndexService;
	public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        Mockery::close();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
    *	@group index
    **/
    public function testIndex()
    {
    	$expected_results = 'index';
    	$this->s_IndexService = new S_IndexService();
    	$result = $this->s_IndexService->index();
    	$this->assertEquals($result,$expected_results);
    }

    /**
    *	@group indexMap
    **/
    public function testIndexMap()
    {
    	$expected_results = 'indexMap';
    	$this->s_IndexService = new S_IndexService();
    	$result = $this->s_IndexService->indexMap();
    	$this->assertEquals($result,$expected_results);
    }
}